// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remote.proto

package remote

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTypeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTypeRequest) Reset()         { *m = GetTypeRequest{} }
func (m *GetTypeRequest) String() string { return proto.CompactTextString(m) }
func (*GetTypeRequest) ProtoMessage()    {}
func (*GetTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{0}
}

func (m *GetTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTypeRequest.Unmarshal(m, b)
}
func (m *GetTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTypeRequest.Marshal(b, m, deterministic)
}
func (m *GetTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTypeRequest.Merge(m, src)
}
func (m *GetTypeRequest) XXX_Size() int {
	return xxx_messageInfo_GetTypeRequest.Size(m)
}
func (m *GetTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTypeRequest proto.InternalMessageInfo

type GetTypeResponse struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTypeResponse) Reset()         { *m = GetTypeResponse{} }
func (m *GetTypeResponse) String() string { return proto.CompactTextString(m) }
func (*GetTypeResponse) ProtoMessage()    {}
func (*GetTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{1}
}

func (m *GetTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTypeResponse.Unmarshal(m, b)
}
func (m *GetTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTypeResponse.Marshal(b, m, deterministic)
}
func (m *GetTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTypeResponse.Merge(m, src)
}
func (m *GetTypeResponse) XXX_Size() int {
	return xxx_messageInfo_GetTypeResponse.Size(m)
}
func (m *GetTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTypeResponse proto.InternalMessageInfo

func (m *GetTypeResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type FromURLRequest struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Properties           map[string]string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FromURLRequest) Reset()         { *m = FromURLRequest{} }
func (m *FromURLRequest) String() string { return proto.CompactTextString(m) }
func (*FromURLRequest) ProtoMessage()    {}
func (*FromURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{2}
}

func (m *FromURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FromURLRequest.Unmarshal(m, b)
}
func (m *FromURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FromURLRequest.Marshal(b, m, deterministic)
}
func (m *FromURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FromURLRequest.Merge(m, src)
}
func (m *FromURLRequest) XXX_Size() int {
	return xxx_messageInfo_FromURLRequest.Size(m)
}
func (m *FromURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FromURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FromURLRequest proto.InternalMessageInfo

func (m *FromURLRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *FromURLRequest) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

type FromURLResponse struct {
	Remote               *_struct.Struct `protobuf:"bytes,1,opt,name=remote,proto3" json:"remote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FromURLResponse) Reset()         { *m = FromURLResponse{} }
func (m *FromURLResponse) String() string { return proto.CompactTextString(m) }
func (*FromURLResponse) ProtoMessage()    {}
func (*FromURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{3}
}

func (m *FromURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FromURLResponse.Unmarshal(m, b)
}
func (m *FromURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FromURLResponse.Marshal(b, m, deterministic)
}
func (m *FromURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FromURLResponse.Merge(m, src)
}
func (m *FromURLResponse) XXX_Size() int {
	return xxx_messageInfo_FromURLResponse.Size(m)
}
func (m *FromURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FromURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FromURLResponse proto.InternalMessageInfo

func (m *FromURLResponse) GetRemote() *_struct.Struct {
	if m != nil {
		return m.Remote
	}
	return nil
}

type ToURLRequest struct {
	Remote               *_struct.Struct `protobuf:"bytes,1,opt,name=remote,proto3" json:"remote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ToURLRequest) Reset()         { *m = ToURLRequest{} }
func (m *ToURLRequest) String() string { return proto.CompactTextString(m) }
func (*ToURLRequest) ProtoMessage()    {}
func (*ToURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{4}
}

func (m *ToURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToURLRequest.Unmarshal(m, b)
}
func (m *ToURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToURLRequest.Marshal(b, m, deterministic)
}
func (m *ToURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToURLRequest.Merge(m, src)
}
func (m *ToURLRequest) XXX_Size() int {
	return xxx_messageInfo_ToURLRequest.Size(m)
}
func (m *ToURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToURLRequest proto.InternalMessageInfo

func (m *ToURLRequest) GetRemote() *_struct.Struct {
	if m != nil {
		return m.Remote
	}
	return nil
}

type ToURLResponse struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Properties           map[string]string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ToURLResponse) Reset()         { *m = ToURLResponse{} }
func (m *ToURLResponse) String() string { return proto.CompactTextString(m) }
func (*ToURLResponse) ProtoMessage()    {}
func (*ToURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{5}
}

func (m *ToURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToURLResponse.Unmarshal(m, b)
}
func (m *ToURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToURLResponse.Marshal(b, m, deterministic)
}
func (m *ToURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToURLResponse.Merge(m, src)
}
func (m *ToURLResponse) XXX_Size() int {
	return xxx_messageInfo_ToURLResponse.Size(m)
}
func (m *ToURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToURLResponse proto.InternalMessageInfo

func (m *ToURLResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ToURLResponse) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

type GetParametersRequest struct {
	Remote               *_struct.Struct `protobuf:"bytes,1,opt,name=remote,proto3" json:"remote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetParametersRequest) Reset()         { *m = GetParametersRequest{} }
func (m *GetParametersRequest) String() string { return proto.CompactTextString(m) }
func (*GetParametersRequest) ProtoMessage()    {}
func (*GetParametersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{6}
}

func (m *GetParametersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParametersRequest.Unmarshal(m, b)
}
func (m *GetParametersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParametersRequest.Marshal(b, m, deterministic)
}
func (m *GetParametersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParametersRequest.Merge(m, src)
}
func (m *GetParametersRequest) XXX_Size() int {
	return xxx_messageInfo_GetParametersRequest.Size(m)
}
func (m *GetParametersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParametersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetParametersRequest proto.InternalMessageInfo

func (m *GetParametersRequest) GetRemote() *_struct.Struct {
	if m != nil {
		return m.Remote
	}
	return nil
}

type GetParametersResponse struct {
	Parameters           *_struct.Struct `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetParametersResponse) Reset()         { *m = GetParametersResponse{} }
func (m *GetParametersResponse) String() string { return proto.CompactTextString(m) }
func (*GetParametersResponse) ProtoMessage()    {}
func (*GetParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{7}
}

func (m *GetParametersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParametersResponse.Unmarshal(m, b)
}
func (m *GetParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParametersResponse.Marshal(b, m, deterministic)
}
func (m *GetParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParametersResponse.Merge(m, src)
}
func (m *GetParametersResponse) XXX_Size() int {
	return xxx_messageInfo_GetParametersResponse.Size(m)
}
func (m *GetParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetParametersResponse proto.InternalMessageInfo

func (m *GetParametersResponse) GetParameters() *_struct.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type ValidateRemoteRequest struct {
	Remote               *_struct.Struct `protobuf:"bytes,1,opt,name=remote,proto3" json:"remote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ValidateRemoteRequest) Reset()         { *m = ValidateRemoteRequest{} }
func (m *ValidateRemoteRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRemoteRequest) ProtoMessage()    {}
func (*ValidateRemoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{8}
}

func (m *ValidateRemoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRemoteRequest.Unmarshal(m, b)
}
func (m *ValidateRemoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRemoteRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRemoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRemoteRequest.Merge(m, src)
}
func (m *ValidateRemoteRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRemoteRequest.Size(m)
}
func (m *ValidateRemoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRemoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRemoteRequest proto.InternalMessageInfo

func (m *ValidateRemoteRequest) GetRemote() *_struct.Struct {
	if m != nil {
		return m.Remote
	}
	return nil
}

type ValidateRemoteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRemoteResponse) Reset()         { *m = ValidateRemoteResponse{} }
func (m *ValidateRemoteResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateRemoteResponse) ProtoMessage()    {}
func (*ValidateRemoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{9}
}

func (m *ValidateRemoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRemoteResponse.Unmarshal(m, b)
}
func (m *ValidateRemoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRemoteResponse.Marshal(b, m, deterministic)
}
func (m *ValidateRemoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRemoteResponse.Merge(m, src)
}
func (m *ValidateRemoteResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateRemoteResponse.Size(m)
}
func (m *ValidateRemoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRemoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRemoteResponse proto.InternalMessageInfo

type ValidateParametersRequest struct {
	Parameters           *_struct.Struct `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ValidateParametersRequest) Reset()         { *m = ValidateParametersRequest{} }
func (m *ValidateParametersRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateParametersRequest) ProtoMessage()    {}
func (*ValidateParametersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{10}
}

func (m *ValidateParametersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateParametersRequest.Unmarshal(m, b)
}
func (m *ValidateParametersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateParametersRequest.Marshal(b, m, deterministic)
}
func (m *ValidateParametersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateParametersRequest.Merge(m, src)
}
func (m *ValidateParametersRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateParametersRequest.Size(m)
}
func (m *ValidateParametersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateParametersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateParametersRequest proto.InternalMessageInfo

func (m *ValidateParametersRequest) GetParameters() *_struct.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type ValidateParametersResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateParametersResponse) Reset()         { *m = ValidateParametersResponse{} }
func (m *ValidateParametersResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateParametersResponse) ProtoMessage()    {}
func (*ValidateParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{11}
}

func (m *ValidateParametersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateParametersResponse.Unmarshal(m, b)
}
func (m *ValidateParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateParametersResponse.Marshal(b, m, deterministic)
}
func (m *ValidateParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateParametersResponse.Merge(m, src)
}
func (m *ValidateParametersResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateParametersResponse.Size(m)
}
func (m *ValidateParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateParametersResponse proto.InternalMessageInfo

type Tag struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Tag_ValueNull
	//	*Tag_ValueString
	Value                isTag_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{12}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type isTag_Value interface {
	isTag_Value()
}

type Tag_ValueNull struct {
	ValueNull bool `protobuf:"varint,2,opt,name=value_null,json=valueNull,proto3,oneof"`
}

type Tag_ValueString struct {
	ValueString string `protobuf:"bytes,3,opt,name=value_string,json=valueString,proto3,oneof"`
}

func (*Tag_ValueNull) isTag_Value() {}

func (*Tag_ValueString) isTag_Value() {}

func (m *Tag) GetValue() isTag_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Tag) GetValueNull() bool {
	if x, ok := m.GetValue().(*Tag_ValueNull); ok {
		return x.ValueNull
	}
	return false
}

func (m *Tag) GetValueString() string {
	if x, ok := m.GetValue().(*Tag_ValueString); ok {
		return x.ValueString
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Tag) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Tag_ValueNull)(nil),
		(*Tag_ValueString)(nil),
	}
}

type Commit struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Properties           *_struct.Struct `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{13}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Commit) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

type GetCommitRequest struct {
	Properties           *_struct.Struct `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	Parameters           *_struct.Struct `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	CommitId             string          `protobuf:"bytes,3,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetCommitRequest) Reset()         { *m = GetCommitRequest{} }
func (m *GetCommitRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommitRequest) ProtoMessage()    {}
func (*GetCommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{14}
}

func (m *GetCommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitRequest.Unmarshal(m, b)
}
func (m *GetCommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitRequest.Marshal(b, m, deterministic)
}
func (m *GetCommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitRequest.Merge(m, src)
}
func (m *GetCommitRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommitRequest.Size(m)
}
func (m *GetCommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitRequest proto.InternalMessageInfo

func (m *GetCommitRequest) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *GetCommitRequest) GetParameters() *_struct.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *GetCommitRequest) GetCommitId() string {
	if m != nil {
		return m.CommitId
	}
	return ""
}

type GetCommitResponse struct {
	// Types that are valid to be assigned to Commit:
	//	*GetCommitResponse_CommitNull
	//	*GetCommitResponse_CommitValue
	Commit               isGetCommitResponse_Commit `protobuf_oneof:"commit"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetCommitResponse) Reset()         { *m = GetCommitResponse{} }
func (m *GetCommitResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommitResponse) ProtoMessage()    {}
func (*GetCommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{15}
}

func (m *GetCommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitResponse.Unmarshal(m, b)
}
func (m *GetCommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitResponse.Marshal(b, m, deterministic)
}
func (m *GetCommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitResponse.Merge(m, src)
}
func (m *GetCommitResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommitResponse.Size(m)
}
func (m *GetCommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitResponse proto.InternalMessageInfo

type isGetCommitResponse_Commit interface {
	isGetCommitResponse_Commit()
}

type GetCommitResponse_CommitNull struct {
	CommitNull bool `protobuf:"varint,1,opt,name=commit_null,json=commitNull,proto3,oneof"`
}

type GetCommitResponse_CommitValue struct {
	CommitValue *Commit `protobuf:"bytes,2,opt,name=commit_value,json=commitValue,proto3,oneof"`
}

func (*GetCommitResponse_CommitNull) isGetCommitResponse_Commit() {}

func (*GetCommitResponse_CommitValue) isGetCommitResponse_Commit() {}

func (m *GetCommitResponse) GetCommit() isGetCommitResponse_Commit {
	if m != nil {
		return m.Commit
	}
	return nil
}

func (m *GetCommitResponse) GetCommitNull() bool {
	if x, ok := m.GetCommit().(*GetCommitResponse_CommitNull); ok {
		return x.CommitNull
	}
	return false
}

func (m *GetCommitResponse) GetCommitValue() *Commit {
	if x, ok := m.GetCommit().(*GetCommitResponse_CommitValue); ok {
		return x.CommitValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetCommitResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetCommitResponse_CommitNull)(nil),
		(*GetCommitResponse_CommitValue)(nil),
	}
}

type ListCommitRequest struct {
	Properties           *_struct.Struct `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	Paramegers           *_struct.Struct `protobuf:"bytes,2,opt,name=paramegers,proto3" json:"paramegers,omitempty"`
	Tags                 []*Tag          `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListCommitRequest) Reset()         { *m = ListCommitRequest{} }
func (m *ListCommitRequest) String() string { return proto.CompactTextString(m) }
func (*ListCommitRequest) ProtoMessage()    {}
func (*ListCommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{16}
}

func (m *ListCommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommitRequest.Unmarshal(m, b)
}
func (m *ListCommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommitRequest.Marshal(b, m, deterministic)
}
func (m *ListCommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommitRequest.Merge(m, src)
}
func (m *ListCommitRequest) XXX_Size() int {
	return xxx_messageInfo_ListCommitRequest.Size(m)
}
func (m *ListCommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommitRequest proto.InternalMessageInfo

func (m *ListCommitRequest) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ListCommitRequest) GetParamegers() *_struct.Struct {
	if m != nil {
		return m.Paramegers
	}
	return nil
}

func (m *ListCommitRequest) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ListCommitResponse struct {
	Commits              []*Commit `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListCommitResponse) Reset()         { *m = ListCommitResponse{} }
func (m *ListCommitResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommitResponse) ProtoMessage()    {}
func (*ListCommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{17}
}

func (m *ListCommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommitResponse.Unmarshal(m, b)
}
func (m *ListCommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommitResponse.Marshal(b, m, deterministic)
}
func (m *ListCommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommitResponse.Merge(m, src)
}
func (m *ListCommitResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommitResponse.Size(m)
}
func (m *ListCommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommitResponse proto.InternalMessageInfo

func (m *ListCommitResponse) GetCommits() []*Commit {
	if m != nil {
		return m.Commits
	}
	return nil
}

func init() {
	proto.RegisterType((*GetTypeRequest)(nil), "remote.GetTypeRequest")
	proto.RegisterType((*GetTypeResponse)(nil), "remote.GetTypeResponse")
	proto.RegisterType((*FromURLRequest)(nil), "remote.FromURLRequest")
	proto.RegisterMapType((map[string]string)(nil), "remote.FromURLRequest.PropertiesEntry")
	proto.RegisterType((*FromURLResponse)(nil), "remote.FromURLResponse")
	proto.RegisterType((*ToURLRequest)(nil), "remote.ToURLRequest")
	proto.RegisterType((*ToURLResponse)(nil), "remote.ToURLResponse")
	proto.RegisterMapType((map[string]string)(nil), "remote.ToURLResponse.PropertiesEntry")
	proto.RegisterType((*GetParametersRequest)(nil), "remote.GetParametersRequest")
	proto.RegisterType((*GetParametersResponse)(nil), "remote.GetParametersResponse")
	proto.RegisterType((*ValidateRemoteRequest)(nil), "remote.ValidateRemoteRequest")
	proto.RegisterType((*ValidateRemoteResponse)(nil), "remote.ValidateRemoteResponse")
	proto.RegisterType((*ValidateParametersRequest)(nil), "remote.ValidateParametersRequest")
	proto.RegisterType((*ValidateParametersResponse)(nil), "remote.ValidateParametersResponse")
	proto.RegisterType((*Tag)(nil), "remote.Tag")
	proto.RegisterType((*Commit)(nil), "remote.Commit")
	proto.RegisterType((*GetCommitRequest)(nil), "remote.GetCommitRequest")
	proto.RegisterType((*GetCommitResponse)(nil), "remote.GetCommitResponse")
	proto.RegisterType((*ListCommitRequest)(nil), "remote.ListCommitRequest")
	proto.RegisterType((*ListCommitResponse)(nil), "remote.ListCommitResponse")
}

func init() { proto.RegisterFile("remote.proto", fileDescriptor_eefc82927d57d89b) }

var fileDescriptor_eefc82927d57d89b = []byte{
	// 703 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdb, 0x4e, 0xdb, 0x40,
	0x10, 0xc5, 0x09, 0x24, 0x64, 0x1c, 0x02, 0xac, 0xb8, 0x18, 0x97, 0x16, 0xd8, 0x8a, 0x8a, 0xa7,
	0x20, 0x85, 0x4a, 0xad, 0x90, 0x7a, 0x11, 0x2d, 0x84, 0x4a, 0xa8, 0xa5, 0x26, 0xe5, 0xa5, 0x0f,
	0xc8, 0x90, 0xc5, 0xb2, 0x70, 0x62, 0xd7, 0x5e, 0x57, 0xca, 0xe7, 0xf4, 0xa5, 0x55, 0x7f, 0xa1,
	0x5f, 0x57, 0x79, 0x77, 0xec, 0xf8, 0x46, 0xa1, 0x51, 0xfb, 0x66, 0xcf, 0x9c, 0x73, 0x66, 0xe6,
	0xac, 0x77, 0x0c, 0x4d, 0x9f, 0x0d, 0x5c, 0xce, 0xda, 0x9e, 0xef, 0x72, 0x97, 0xd4, 0xe4, 0x9b,
	0xbe, 0x6e, 0xb9, 0xae, 0xe5, 0xb0, 0x5d, 0x11, 0xbd, 0x0c, 0xaf, 0x77, 0x03, 0xee, 0x87, 0x57,
	0x5c, 0xa2, 0xe8, 0x02, 0xb4, 0xba, 0x8c, 0xf7, 0x46, 0x1e, 0x33, 0xd8, 0x97, 0x90, 0x05, 0x9c,
	0x6e, 0xc3, 0x7c, 0x12, 0x09, 0x3c, 0x77, 0x18, 0x30, 0x42, 0x60, 0x9a, 0x8f, 0x3c, 0xa6, 0x29,
	0x9b, 0xca, 0x4e, 0xc3, 0x10, 0xcf, 0xf4, 0xa7, 0x02, 0xad, 0x23, 0xdf, 0x1d, 0x7c, 0x32, 0x4e,
	0x90, 0x49, 0x16, 0xa0, 0x1a, 0xfa, 0x0e, 0xa2, 0xa2, 0x47, 0x72, 0x04, 0xe0, 0xf9, 0xae, 0xc7,
	0x7c, 0x6e, 0xb3, 0x40, 0xab, 0x6c, 0x56, 0x77, 0xd4, 0xce, 0x93, 0x36, 0xb6, 0x99, 0x65, 0xb7,
	0x4f, 0x13, 0xe0, 0xe1, 0x90, 0xfb, 0x23, 0x23, 0xc5, 0xd4, 0x5f, 0xc0, 0x7c, 0x2e, 0x1d, 0x15,
	0xbb, 0x61, 0xa3, 0xb8, 0xd8, 0x0d, 0x1b, 0x91, 0x25, 0x98, 0xf9, 0x6a, 0x3a, 0x21, 0xd3, 0x2a,
	0x22, 0x26, 0x5f, 0xf6, 0x2b, 0xcf, 0x15, 0x7a, 0x00, 0xf3, 0x49, 0x31, 0x1c, 0x69, 0x17, 0xd0,
	0x1f, 0xa1, 0xa0, 0x76, 0x56, 0xdb, 0xd2, 0xa6, 0x76, 0x6c, 0x53, 0xfb, 0x4c, 0xd8, 0x64, 0x20,
	0x8c, 0xbe, 0x82, 0x66, 0xcf, 0x4d, 0x0d, 0xfb, 0xd7, 0x02, 0x3f, 0x14, 0x98, 0x43, 0x05, 0xec,
	0xa1, 0xe8, 0xd7, 0x61, 0x89, 0x5f, 0xdb, 0xb1, 0x5f, 0x19, 0xf2, 0xff, 0xb4, 0xab, 0x0b, 0x4b,
	0x5d, 0xc6, 0x4f, 0x4d, 0xdf, 0x1c, 0x30, 0xce, 0xfc, 0x60, 0xe2, 0x91, 0x4f, 0x61, 0x39, 0x27,
	0x84, 0x93, 0x3f, 0x03, 0xf0, 0x92, 0xe8, 0x5d, 0x6a, 0x29, 0x28, 0x3d, 0x86, 0xe5, 0x73, 0xd3,
	0xb1, 0xfb, 0x26, 0x67, 0x86, 0xa8, 0x31, 0x71, 0x6f, 0x1a, 0xac, 0xe4, 0x95, 0x64, 0x73, 0xb4,
	0x07, 0x6b, 0x71, 0xa6, 0xe8, 0xc1, 0xc4, 0x9d, 0xaf, 0x83, 0x5e, 0xa6, 0x8a, 0x35, 0xaf, 0xa1,
	0xda, 0x33, 0xad, 0x92, 0x53, 0xda, 0x00, 0x10, 0x07, 0x73, 0x31, 0x0c, 0x1d, 0x47, 0x1c, 0xd5,
	0xec, 0xf1, 0x94, 0xd1, 0x10, 0xb1, 0xf7, 0xa1, 0xe3, 0x90, 0xc7, 0xd0, 0x94, 0x80, 0x80, 0xfb,
	0xf6, 0xd0, 0xd2, 0xaa, 0x11, 0xf7, 0x78, 0xca, 0x50, 0x45, 0xf4, 0x4c, 0x04, 0x0f, 0xea, 0x78,
	0xd6, 0xf4, 0x23, 0xd4, 0xde, 0xb8, 0x83, 0x81, 0xcd, 0x49, 0x0b, 0x2a, 0x76, 0x1f, 0x2b, 0x55,
	0xec, 0xbe, 0x18, 0x2c, 0xfd, 0xe9, 0xdd, 0x31, 0x58, 0x02, 0xa5, 0xdf, 0x14, 0x58, 0xe8, 0x32,
	0x2e, 0x65, 0xd3, 0x36, 0x8d, 0xd5, 0x94, 0x7b, 0xab, 0xe5, 0xfc, 0xad, 0xdc, 0xdb, 0x5f, 0xf2,
	0x00, 0x1a, 0x57, 0xa2, 0x85, 0x0b, 0xbb, 0x2f, 0x4d, 0x30, 0x66, 0x65, 0xe0, 0x5d, 0x9f, 0x86,
	0xb0, 0x98, 0x6a, 0x11, 0x3f, 0xc2, 0x2d, 0x50, 0x91, 0x21, 0xbc, 0x55, 0xd0, 0x5b, 0x90, 0x41,
	0x61, 0xee, 0x1e, 0x34, 0x11, 0x32, 0xbe, 0x2a, 0x6a, 0xa7, 0x15, 0xdf, 0x48, 0x29, 0x18, 0x99,
	0x2d, 0x51, 0xe7, 0x11, 0xe8, 0x60, 0x16, 0x6a, 0xf2, 0x95, 0x7e, 0x57, 0x60, 0xf1, 0xc4, 0x0e,
	0xfe, 0xb9, 0x37, 0xd6, 0xfd, 0xbd, 0x89, 0xa0, 0x64, 0x03, 0xa6, 0xb9, 0x69, 0x05, 0x5a, 0x55,
	0x2c, 0x14, 0x35, 0x59, 0x28, 0xa6, 0x65, 0x88, 0x04, 0x7d, 0x09, 0x24, 0xdd, 0x27, 0x1a, 0xb4,
	0x03, 0x75, 0x39, 0x48, 0xd4, 0x65, 0xb5, 0x38, 0xb8, 0x11, 0xa7, 0x3b, 0xbf, 0xa6, 0xa1, 0x26,
	0x6f, 0x11, 0xd9, 0x87, 0x3a, 0xfe, 0x3e, 0xc8, 0x4a, 0x0c, 0xcf, 0xfe, 0x61, 0xf4, 0xd5, 0x42,
	0x1c, 0x0b, 0xee, 0x43, 0x1d, 0xf7, 0xf4, 0x98, 0x9b, 0xfd, 0x4b, 0x8c, 0xb9, 0xf9, 0x85, 0xfe,
	0x14, 0x66, 0xc4, 0x82, 0x24, 0x4b, 0xb9, 0x7d, 0x29, 0x79, 0xcb, 0xa5, 0x5b, 0x94, 0x9c, 0xc0,
	0x5c, 0x66, 0x43, 0x91, 0xf5, 0x54, 0x6f, 0x85, 0xdb, 0xaf, 0x3f, 0xbc, 0x25, 0x8b, 0x6a, 0x1f,
	0xa0, 0x95, 0xdd, 0x29, 0x24, 0x21, 0x94, 0x6e, 0x2d, 0xfd, 0xd1, 0x6d, 0x69, 0x14, 0xfc, 0x0c,
	0xa4, 0xb8, 0x34, 0xc8, 0x56, 0x9e, 0x55, 0x6c, 0x94, 0xfe, 0x09, 0x82, 0xe2, 0x6f, 0x41, 0x1d,
	0x1f, 0x7a, 0x40, 0xd6, 0x62, 0x4a, 0xe1, 0x8b, 0xd5, 0xf5, 0xb2, 0x14, 0xaa, 0xbc, 0x86, 0x46,
	0x72, 0xb5, 0x88, 0x96, 0xf2, 0x27, 0x2b, 0xb1, 0x56, 0x92, 0x91, 0x0a, 0x97, 0x35, 0xf1, 0xe9,
	0xee, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x96, 0xc4, 0x67, 0x70, 0xbf, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteClient is the client API for Remote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteClient interface {
	GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*GetTypeResponse, error)
	FromURL(ctx context.Context, in *FromURLRequest, opts ...grpc.CallOption) (*FromURLResponse, error)
	ToURL(ctx context.Context, in *ToURLRequest, opts ...grpc.CallOption) (*ToURLResponse, error)
	GetParameters(ctx context.Context, in *GetParametersRequest, opts ...grpc.CallOption) (*GetParametersResponse, error)
	ValidateRemote(ctx context.Context, in *ValidateRemoteRequest, opts ...grpc.CallOption) (*ValidateRemoteResponse, error)
	ValidateParameters(ctx context.Context, in *ValidateParametersRequest, opts ...grpc.CallOption) (*ValidateParametersResponse, error)
	ListCommits(ctx context.Context, in *ListCommitRequest, opts ...grpc.CallOption) (*ListCommitResponse, error)
	GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*GetCommitResponse, error)
}

type remoteClient struct {
	cc *grpc.ClientConn
}

func NewRemoteClient(cc *grpc.ClientConn) RemoteClient {
	return &remoteClient{cc}
}

func (c *remoteClient) GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*GetTypeResponse, error) {
	out := new(GetTypeResponse)
	err := c.cc.Invoke(ctx, "/remote.Remote/GetType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteClient) FromURL(ctx context.Context, in *FromURLRequest, opts ...grpc.CallOption) (*FromURLResponse, error) {
	out := new(FromURLResponse)
	err := c.cc.Invoke(ctx, "/remote.Remote/FromURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteClient) ToURL(ctx context.Context, in *ToURLRequest, opts ...grpc.CallOption) (*ToURLResponse, error) {
	out := new(ToURLResponse)
	err := c.cc.Invoke(ctx, "/remote.Remote/ToURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteClient) GetParameters(ctx context.Context, in *GetParametersRequest, opts ...grpc.CallOption) (*GetParametersResponse, error) {
	out := new(GetParametersResponse)
	err := c.cc.Invoke(ctx, "/remote.Remote/GetParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteClient) ValidateRemote(ctx context.Context, in *ValidateRemoteRequest, opts ...grpc.CallOption) (*ValidateRemoteResponse, error) {
	out := new(ValidateRemoteResponse)
	err := c.cc.Invoke(ctx, "/remote.Remote/ValidateRemote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteClient) ValidateParameters(ctx context.Context, in *ValidateParametersRequest, opts ...grpc.CallOption) (*ValidateParametersResponse, error) {
	out := new(ValidateParametersResponse)
	err := c.cc.Invoke(ctx, "/remote.Remote/ValidateParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteClient) ListCommits(ctx context.Context, in *ListCommitRequest, opts ...grpc.CallOption) (*ListCommitResponse, error) {
	out := new(ListCommitResponse)
	err := c.cc.Invoke(ctx, "/remote.Remote/ListCommits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteClient) GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*GetCommitResponse, error) {
	out := new(GetCommitResponse)
	err := c.cc.Invoke(ctx, "/remote.Remote/GetCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteServer is the server API for Remote service.
type RemoteServer interface {
	GetType(context.Context, *GetTypeRequest) (*GetTypeResponse, error)
	FromURL(context.Context, *FromURLRequest) (*FromURLResponse, error)
	ToURL(context.Context, *ToURLRequest) (*ToURLResponse, error)
	GetParameters(context.Context, *GetParametersRequest) (*GetParametersResponse, error)
	ValidateRemote(context.Context, *ValidateRemoteRequest) (*ValidateRemoteResponse, error)
	ValidateParameters(context.Context, *ValidateParametersRequest) (*ValidateParametersResponse, error)
	ListCommits(context.Context, *ListCommitRequest) (*ListCommitResponse, error)
	GetCommit(context.Context, *GetCommitRequest) (*GetCommitResponse, error)
}

// UnimplementedRemoteServer can be embedded to have forward compatible implementations.
type UnimplementedRemoteServer struct {
}

func (*UnimplementedRemoteServer) GetType(ctx context.Context, req *GetTypeRequest) (*GetTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetType not implemented")
}
func (*UnimplementedRemoteServer) FromURL(ctx context.Context, req *FromURLRequest) (*FromURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FromURL not implemented")
}
func (*UnimplementedRemoteServer) ToURL(ctx context.Context, req *ToURLRequest) (*ToURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToURL not implemented")
}
func (*UnimplementedRemoteServer) GetParameters(ctx context.Context, req *GetParametersRequest) (*GetParametersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParameters not implemented")
}
func (*UnimplementedRemoteServer) ValidateRemote(ctx context.Context, req *ValidateRemoteRequest) (*ValidateRemoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateRemote not implemented")
}
func (*UnimplementedRemoteServer) ValidateParameters(ctx context.Context, req *ValidateParametersRequest) (*ValidateParametersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateParameters not implemented")
}
func (*UnimplementedRemoteServer) ListCommits(ctx context.Context, req *ListCommitRequest) (*ListCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCommits not implemented")
}
func (*UnimplementedRemoteServer) GetCommit(ctx context.Context, req *GetCommitRequest) (*GetCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommit not implemented")
}

func RegisterRemoteServer(s *grpc.Server, srv RemoteServer) {
	s.RegisterService(&_Remote_serviceDesc, srv)
}

func _Remote_GetType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).GetType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.Remote/GetType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).GetType(ctx, req.(*GetTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remote_FromURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FromURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).FromURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.Remote/FromURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).FromURL(ctx, req.(*FromURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remote_ToURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).ToURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.Remote/ToURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).ToURL(ctx, req.(*ToURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remote_GetParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).GetParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.Remote/GetParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).GetParameters(ctx, req.(*GetParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remote_ValidateRemote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRemoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).ValidateRemote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.Remote/ValidateRemote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).ValidateRemote(ctx, req.(*ValidateRemoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remote_ValidateParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).ValidateParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.Remote/ValidateParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).ValidateParameters(ctx, req.(*ValidateParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remote_ListCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).ListCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.Remote/ListCommits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).ListCommits(ctx, req.(*ListCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remote_GetCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).GetCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.Remote/GetCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).GetCommit(ctx, req.(*GetCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Remote_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remote.Remote",
	HandlerType: (*RemoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetType",
			Handler:    _Remote_GetType_Handler,
		},
		{
			MethodName: "FromURL",
			Handler:    _Remote_FromURL_Handler,
		},
		{
			MethodName: "ToURL",
			Handler:    _Remote_ToURL_Handler,
		},
		{
			MethodName: "GetParameters",
			Handler:    _Remote_GetParameters_Handler,
		},
		{
			MethodName: "ValidateRemote",
			Handler:    _Remote_ValidateRemote_Handler,
		},
		{
			MethodName: "ValidateParameters",
			Handler:    _Remote_ValidateParameters_Handler,
		},
		{
			MethodName: "ListCommits",
			Handler:    _Remote_ListCommits_Handler,
		},
		{
			MethodName: "GetCommit",
			Handler:    _Remote_GetCommit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remote.proto",
}
